 Dataset URL https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification?resource=download


### Context

Bob has started his own mobile company. He wants to give tough fight to big companies like Apple,Samsung etc.

He does not know how to estimate price of mobiles his company creates. In this competitive mobile phone market you cannot simply assume things. To solve this problem he collects sales data of mobile phones of various companies.

Bob wants to find out some relation between features of a mobile phone(eg:- RAM,Internal Memory etc) and its selling price. But he is not so good at Machine Learning. So he needs your help to solve this problem.

In this problem you do not have to predict actual price but a price range indicating how high the price is


### Columns Desscription (excluding id)

1. battery_power -- Total energy a battery can store in one time measured in mAh
2. blue --  Has bluetooth or not
3. clock_speed -- speed at which microprocessor executes instructions
4. dual_sim -- Has dual sim support or not
5. fc -- Front Camera mega pixels
6. four_g -- Has 4G or not
7. int_memory -- Internal Memory in Gigabytes
8. m_dep -- Mobile Depth in cm
9. mobile_wt -- Weight of mobile phone
10. n_cores -- Number of cores of processor
11. pc -- Primary Camera mega pixels
12. px_height -- Pixel Resolution Height
13. px_width -- Pixel Resolution Width
14. ram -- Random Access Memory in Megabytes
15. sc_h -- Screen Height of mobile in cm
16. sc_w -- Screen Width of mobile in cm
17. talk_time -- longest time that a single battery charge will last when you are
18. three_g -- Has 3G or not
19. touch_screen -- Has touch screen 
20. wifi -- Has wifi or not
21. price_range -- expected output 

#### Price Range Values:

- 0 - low cost
- 1 - medium cost
- 2 - high cost
- 3 - very high cost

In [31]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\kuda\appdata\local\programs\python\python312\lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\kuda\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.1.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\kuda\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\kuda\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\kuda\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
#importing libraries

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd;

In [33]:
#Reading the training data into python


training = pd.read_csv("train.csv")
#training.head(10) #viewing the first 10 elements
#training.tail(10)  #viewing the last 10 elements

training.isnull().sum().sum() #counting missing values

np.int64(0)

In [34]:
#Reading the testing data into python


testing = pd.read_csv("test.csv")
#testing.head(10) #viewing the first 10 elements
#testing.tail(10)  #viewing the last 10 elements

testing.isnull().sum().sum() #counting missing values 

testing.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1

In [26]:
#Split the  training data into output and inpit

input = training.drop(['price_range'],axis=1)
output = training['price_range']

output.shape, input.shape

((2000,), (2000, 20))

In [37]:
#Split the  training data into output and inpit

test_input = testing.drop(['id'],axis=1)
#test_output = testing['price_range']

test_input.shape

(1000, 20)

### Support Vector Machine Classifier

In [40]:
svm = SVC()

svm.fit(input,output)

test_output = svm.predict(test_input)

In [41]:
# ssave model results to a fie

# Example: Create a DataFrame with Id and prediction columns
submission = pd.DataFrame({
    'Id': testing['id'],  # Replace 'Id' with the actual identifier column in your dataset (like PassengerId, etc.)
    'Predicted': test_output
})

# Save the submission to a CSV file
submission.to_csv('submission.csv', index=False)

# Check the first few rows of the submission file
submission.head()

   Id  Predicted
0   1          3
1   2          3
2   3          2
3   4          3
4   5          1